spring:
  config: 
    activate:
      on-profile: dev
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    
    properties:
      hibernate:
        ddl-auto: validate
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver 